### PR TITLE
Identify and register "coordinator" devices only in paired/grouped setups

### PR DESCRIPTION
**Pull request by fwboettger**
**@nfarina** i'd like to propose this change which i believe does resolve the issue “Intermittent error on startup, with paired Play 1's #4” (https://github.com/nfarina/homebridge-sonos/issues/4).

The code changes (based on code samples from node-sones) in index.js now identify the current “coordinator” sonos device for a respective zone (room) and register these as homekit accessories.
Tested in my environment at home (playbar with sub and 2 play3 paired
to a 5.1 surround setup in the living room, and several non-paired
individual devices in other rooms).

### CODE REVIEW

**Comment by adamstephenson** [comment]
@fwboettger, this is a great improvement -- thanks! +1 

Can you confirm testing with groups too? It looks like the coordinator designator would work in that situation as well -- as you also imply in your comment "...paired/grouped..."  

Thanks again!

**Comment by fwboettger** [comment]
Dear @adamstephenson, thanks much! Confirm partial Tests for groups, but didnt have time to conduct extensively here as i've been flying of with the Family to a short vacation today.... In any case, pairing typically is pretty static once setup, grouping usually is way more dynamic i believe, and in Order to cater to this (Dynamic changes to the topology), i believe one needs to subscribe to respective events and react accordingly. Wanted to look into this separately after my return (seems to be a bit more complex).....

**Comment by Nousemusic** [comment]
@adamstephenson or @fwboettger can you help me install the changes?

Do I have to edit the home bridge-sonos plugin's index.js by hand or can I just reinstall the whole plugin via npm install -g homebridge-sonos?

Thank you for your help in advance.

**Comment by fwboettger** [comment]
@Nousemusic - for now you need to edit the index.js by hand i'm afraid. The pull request isn't yet been incorporated into the plugin's package, hence reinstalling would simply not include the changes....

**Comment by Nousemusic** [comment]
@fwboettger thanks for the reply. I'll try to edit the files by hand.

do I have to add the new config value named "udn" to every paired/ grouped accessory? and only to the paired/ grouped accessories?

**Pull request merged**
